/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neoend_gms_util_SystemCommandJNI */

#ifndef _Included_com_neoend_gms_util_SystemCommandJNI
#define _Included_com_neoend_gms_util_SystemCommandJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_neoend_gms_util_SystemCommandJNI
 * Method:    getprop
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_neoend_gms_util_SystemCommandJNI_getprop
  (JNIEnv *, jobject);

/*
 * Class:     com_neoend_gms_util_SystemCommandJNI
 * Method:    execute
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_neoend_gms_util_SystemCommandJNI_execute
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
